### ISSUE TITLE
Set a Default Gravatar

### ISSUE THREAD

**Issue by BrookeDot** [koel/core#33]
Currently the default Gravatar is the blue G logo. We can pass a URL to the `d` parameter and customize the logo. 
https://en.gravatar.com/site/implement/images/

This could either be the Koel logo or a mystery person logo. It should be a square that is 256x256

Let me know your thoughts and I'll get it setup

**Comment by BrookeDot** [comment]
What about using the standard Font Awesome icon? If so I can make a simple square 256x256 icon and we can use that.
https://fontawesome.com/icons/user?style=solid

**Comment by phanan** [comment]
I don't get it. What's wrong with the default G?

**Comment by BrookeDot** [comment]
Nothing is wrong per se. Just thinking that a default person would be more visually appealing and less Gravatar branded. 

If I wasn't aware of what a Gravatar was I don't think I would understand what the "G" meant. Changing the icon to a person makes it more clear for those without a Gravatar that that is where they can manage their profile.

In fact, I think we should take it a step further and also mention Gravatar either on the profile page linking to where users can change their icon. (but that's another discussion)

WordPress itself does this by providing different default options including allowed generated Gravatars with the Mystery Person being the default.
<img width="1131" alt="Screen Shot 2020-04-24 at 11 07 22 PM" src="https://user-images.githubusercontent.com/150348/80272694-8b58a600-8680-11ea-84ea-b7045a44b2bd.png">

**Comment by phanan** [comment]
Right. Let's use the "mystery person" then?

**Comment by phanan** [comment]
@BrookeDot Do you still want to tackle this?

**Comment by BrookeDot** [comment]
Sure, I've never done much with Vue or TypeScript but this seems like one I can handle, I created a Pull Request:
https://github.com/koel/core/pull/48

The test images look correct:
https://www.gravatar.com/avatar/5024672cfe53f113b746e1923e373058?s=256&d=mp
https://www.gravatar.com/avatar/b9611f1bba1aacbe6f5de5856695a202?s=256&d=mp
