### ISSUE TITLE
Can't load song 

### ISSUE THREAD

**Issue by kaiweia** [koel/core#44]
koel version 4.4.0
- url is wrong, should be `api/${song.id}/play/1/128`
- server accepts `jwt-token` but you use `api-token`
https://github.com/koel/core/blob/31adae0b3c68c9b07c33d0f13bf4c2dd565a9746/js/stores/song.ts#L200-L205

**Comment by phanan** [comment]
You appear to be using the `master` branch of `core` (client) against the 4.4.0 tag of API.
