### ISSUE TITLE
Albums not reactive with 3.7.2

### ISSUE THREAD

**Issue by patric-eberle** [koel/core#9]
When I did testings with version 3.7.2 of Koel and changed the compilation state of songs, I discovered, that the album section of of the Vue app was not updated correctly. It looks like `albumStore.all` is not reactive. When old albums are removed from the store and replaced with new ones, the Vue components are not destroyed and replaced with new ones.

https://github.com/koel/core/blob/de29c0b2f677c821e7305ab59bfc5da457a77902/js/components/screens/album-list.vue#L54

**Comment by phanan** [comment]
I believe this has been solved in more recent versions :)
